In [22]:
!pip install numpy


import numpy as np
from .testing import Tester





Defaulting to user installation because normal site-packages is not writeable


ImportError: attempted relative import with no known parent package

In [6]:
a = np.array([1,2,3,4])

In [7]:
a

array([1, 2, 3, 4])

In [10]:
print (a[2])

3


In [14]:
a = np.zeros([2])
a


array([0., 0.])

In [18]:
a = np.ones([2])
a

array([1., 1.])

In [20]:
a = np.empty([2])

In [21]:
a = np.arrage([4])

AttributeError: module 'numpy' has no attribute 'arrage'